name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: fathymhmedx

          # ----------------------------
          # Theme
          # ----------------------------
          template: classic
          base: header, activity
          config_timezone: Africa/Cairo

          # ----------------------------
          # Languages
          # ----------------------------
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_recent_days: 365

          # ----------------------------
          # Contribution Calendar
          # ----------------------------
          plugin_isocalendar: yes

          # ----------------------------
          # Commit Streak
          # ----------------------------
          plugin_followup: yes

          # ----------------------------
          # Disable Everything Else
          # ----------------------------
          plugin_topics: no
          plugin_habits: no
          plugin_achievements: no
          plugin_repositories: no
          plugin_stars: no
          plugin_lines: no
          plugin_discussions: no
          plugin_introduction: no
          plugin_notable: no
          plugin_people: no
          plugin_projects: no
          plugin_reactions: no
          plugin_sponsors: no
          plugin_traffic: no
          plugin_gists: no
          plugin_pagespeed: no
          plugin_wakatime: no
